"""empty message

Revision ID: e6a38ac80bb8
Revises: fcc528c9d1bf
Create Date: 2025-12-03 21:03:15.444011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e6a38ac80bb8'
down_revision: Union[str, Sequence[str], None] = 'fcc528c9d1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invernadero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invernadero', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
