"""empty message

Revision ID: eaf485562f49
Revises: e6a38ac80bb8
Create Date: 2025-12-04 03:23:40.666833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'eaf485562f49'
down_revision: Union[str, Sequence[str], None] = 'e6a38ac80bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_confirmacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendario', schema=None) as batch_op:
        batch_op.drop_column('ultima_confirmacion')

    # ### end Alembic commands ###
