"""empty message

Revision ID: fcc528c9d1bf
Revises: b5acf5cb948f
Create Date: 2025-11-30 09:25:00.989441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fcc528c9d1bf'
down_revision: Union[str, Sequence[str], None] = 'b5acf5cb948f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invernadero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Humedad', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Temperatura', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('Nivel_Agua', sa.Float(), nullable=False))
        batch_op.drop_column('Nivel_Agua_Actual')
        batch_op.drop_column('Temperatura_Actual')
        batch_op.drop_column('Humedad_Actual')

    with op.batch_alter_table('planta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('temperatura',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('humedad',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('nivel_agua',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('nivel_agua',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('humedad',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperatura',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('planta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('invernadero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Humedad_Actual', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Temperatura_Actual', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('Nivel_Agua_Actual', sa.FLOAT(), nullable=True))
        batch_op.drop_column('Nivel_Agua')
        batch_op.drop_column('Temperatura')
        batch_op.drop_column('Humedad')

    # ### end Alembic commands ###
